language: node_js
node_js:
  - "0.4"
  - "0.6"
  - "0.8"
  - "0.9"
  - "0.10"
  - "0.11.3"
  - "0.11.4"
  - "0.11.10"
  - "0.11.11"
  - "0.11.12"
matrix:
  allow_failures:
    - node_js: "0.11.10"
    - node_js: "0.11.11"
before_install:
  - echo $TRAVIS_NODE_VERSION
  - echo "${TRAVIS_NODE_VERSION}"
  - |
    if [ "${TRAVIS_NODE_VERSION}" != "0.4" ]
    then
      rm -rf ~/.nvm
      wget -qO- https://raw.github.com/creationix/nvm/v0.5.1/install.sh | sh
      source ~/.nvm/nvm.sh
      nvm install "${TRAVIS_NODE_VERSION}"
      nvm use "${TRAVIS_NODE_VERSION}"
    fi
  - node --version
